### ISSUE TITLE
Cannot Add custom Token 

### ISSUE THREAD

**Issue by pro-fish** [Wardenswap/warden-protocol#2]
Hello guys , 

To keep this short , **there is no way on UI to add a custom Token Via contract address** !
 
your project is an AMM aggregator with **10/10** on every aspect that matter but its literally pointless if the user cant add other unknown token .
the token list is so limited which hurt the project **potential** in terms of : volume / adaptation / accessibly / usefulness .

please consider Adding this feature **ASAP** Before a large amount of people try it and then get drifted to other protocols that provide custom token addition .
Ex.
![Screenshot 2021-03-29 012405](https://user-images.githubusercontent.com/80102780/112770073-a8f16680-8fd9-11eb-96e1-65e570d6ebb2.png)

**thank you guys for this awesome beast  :)** 
_i tried finding another way of contacting the team , unfortunately there was only the twitter account which isn't very useful for discussing technical issues  ._
_note : please consider creating a community channel on discord or any similar apps_

**Comment by WardenInvoker** [comment]
Thanks for your valuable feedback. The custom token loading was actually in our todo list and we have already implemented this feature. You can now load and swap any arbitrary tokens on [wardenswap.finance](https://www.wardenswap.finance/). Happy swapping. 👽

**Comment by pro-fish** [comment]
Perfect, just noticed it yesterday 👌🏻.
thanx guys amazing project .
